services:
  - type: web
    name: go-staff-api
    runtime: node
    plan: free
    rootDir: .
    buildCommand: npm install && npm run build -w @go-staff/shared && npm run prisma:generate -w @go-staff/api && npm run build -w @go-staff/api
    startCommand: npm run start -w @go-staff/api
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: NODE_ENV
        value: production
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: TRUST_PROXY
        value: "true"
      - key: CORS_ORIGIN
        value: https://hrms-app6.vercel.app
      - key: WEB_ORIGIN
        value: https://hrms-app6.vercel.app
      - key: CAREERS_PUBLIC_URL
        value: https://hrms-app6.vercel.app/careers
      - key: MS_REDIRECT_URI
        value: https://hrms-snvh.onrender.com/api/v1/auth/microsoft/callback
      - key: GOOGLE_REDIRECT_URI
        value: https://hrms-snvh.onrender.com/api/v1/calendar/callback
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
